#Number of orders: 2
#Tasks: kitting
#Number of kitting shipments: 2
#Number of assembly shipments: 0
#Insufficiently many products: No
#Part re-orientation: No
#In-process order update: No
#Dropped products: No
#In-process order interruption: Yes
#Faulty products: Yes
#Sensor blackout: Yes
#Time limit: No

options:
  insert_models_over_bins: true
  insert_models_over_stations: false
  gazebo_state_logging: false
  belt_population_cycles: 0
time_limit: -1

agv_infos:
  agv1:
    location: ks1
    products:
      part_0:
        type: assembly_sensor_green
        pose:
          xyz: [-0.1, 0.1, 0]
          rpy: [0, 0, 0]
      
  agv2:
    location: ks2
  agv3:
    location: ks3
  agv4:
    location: ks4    
    
orders:
  order_0:
    priority: 1
    kitting_robot_health: 1 
    assembly_robot_health: 1
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 1
      agvs: [agv1]
      destinations: [as1]
      products:
        part_2:
          type: assembly_sensor_green
          pose:
            xyz: [-0.1, 0.1, 0]
            rpy: [0, 0, 'pi/3']

models_over_bins:
  bin2:
    models:
      assembly_battery_green:
        xyz_start: [0.2, 0.2, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 1
        num_models_y: 1

