#Number of orders: 2
#Tasks: kitting
#Number of kitting shipments: 2
#Number of assembly shipments: 0
#Insufficiently many products: No
#Part re-orientation: No
#In-process order update: No
#Dropped products: No
#In-process order interruption: Yes
#Faulty products: Yes
#Sensor blackout: Yes
#Time limit: No

options:
  insert_models_over_bins: true
  insert_models_over_stations: false
  gazebo_state_logging: false
  belt_population_cycles: 5 
time_limit: -1

agv_infos:
  agv1:
    location: ks1
  agv2:
    location: ks2
  agv3:
    location: ks3
  agv4:
    location: ks4    
    
orders:
  order_0:
    priority: 1
    kitting_robot_health: 1 
    assembly_robot_health: 1
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 1
      agvs: [agv1]
      destinations: [as1]
      products:
        part_0:
          type: assembly_sensor_red
          pose:
            xyz: [-0.1, 0.1, 0]
            rpy: [0, 0, 'pi/3']
        # part_1:
        #   type: assembly_battery_blue
        #   pose:
        #     xyz: [0.1, 0.1, 0]
        #     rpy: [0, 0, 'pi/2']
        # part_2:
        #   type: assembly_regulator_blue
        #   pose:
        #     xyz: [0.1, -0.1, 0]
        #     rpy: [0, 0, 0]
        # part_3:
        #   type: assembly_pump_red
        #   pose:
        #     xyz: [0.1, -0.1, 0]
        #     rpy: [0, 0, 0]

models_over_bins:
  bin2:
    models:
      assembly_sensor_red:
        xyz_start: [0.2, 0.2, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2
  # bin1:
  #   models:
  #     assembly_battery_blue:
  #       xyz_start: [0.2, 0.2, 0.0]
  #       xyz_end: [0.4, 0.4, 0.0]
  #       rpy: [0, 0, 0]
  #       num_models_x: 2
  #       num_models_y: 2
  # bin5:
  #   models:
  #     assembly_regulator_blue:
  #       xyz_start: [0.2, 0.2, 0.0]
  #       xyz_end: [0.4, 0.4, 0.0]
  #       rpy: [0, 0, 0]
  #       num_models_x: 2
  #       num_models_y: 2
  #
  # bin6:
  #   models:
  #     assembly_pump_red:
  #       xyz_start: [0.2, 0.2, 0.0]
  #       xyz_end: [0.4, 0.4, 0.0]
  #       rpy: [0, 0, 0]
  #       num_models_x: 2
        # num_models_y: 2
        #
belt_models:
  assembly_regulator_red:
    15.0:
      pose:
        xyz: [0.0, 4.3, 0.92]
        rpy: [0, 0, 'pi/3']


faulty_products:
  - assembly_battery_blue_1
  - assembly_battery_blue_2
  - assembly_battery_blue_3
  - assembly_battery_blue_4
  - assembly_sensor_red_1
  - assembly_sensor_red_2
  - assembly_sensor_red_3
  - assembly_sensor_red_4
  - assembly_regulator_blue_1
  - assembly_regulator_blue_2
  - assembly_regulator_blue_3
  - assembly_regulator_blue_4
  - assembly_pump_red_1
  - assembly_pump_red_2
  - assembly_pump_red_3
  - assembly_pump_red_4
